import type { Hackathon } from "./types";

const now = new Date().toISOString();

export const SEED_HACKATHONS: Hackathon[] = [
  {
    id: "seed-1",
    name: "Example City Hack 2026",
    organizer: "Example Org",
    location: "Remote",
    isRemote: true,
    startDate: "2026-10-18",
    endDate: "2026-10-19",
    applicationDeadline: "2026-10-10",
    url: "https://example.com",
    status: "planning_to_apply",
    result: "none",
    rank: null,
    prize: null,
    technologies: ["Next.js", "Neon", "Tailwind"],
    teamMembers: [],
    projectName: null,
    projectUrl: null,
    repoUrl: null,
    notes: "Review judging criteria before applying.",
    learnings: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-2",
    name: "Demo Day Build Sprint",
    organizer: "Local Dev Community",
    location: "San Francisco, CA",
    isRemote: false,
    startDate: "2026-08-02",
    endDate: "2026-08-03",
    applicationDeadline: "2026-07-25",
    url: null,
    status: "attended",
    result: "finalist",
    rank: "Top 8 / 60",
    prize: null,
    technologies: ["TypeScript", "Vercel AI SDK"],
    teamMembers: ["Alex", "Sam"],
    projectName: "HackTrack prototype",
    projectUrl: null,
    repoUrl: null,
    notes: "Great mentor feedback on demo flow.",
    learnings: "Ship the demo path first; cut scope early; practice the 2-min pitch.",
    createdAt: now,
    updatedAt: now,
  },
];
